cat("Welcome to the Leah Sohlberg Woods R01 project.\n")
require(dplyr)
require(magrittr)
require(data.table)
require(tidyverse)
require(readxl)

# install.packages('splitstackshape')
# install.packages('janitor')
require(splitstackshape)
require(janitor)
require(stringr)
require(ggplot2)
require(tidyxl)

library(dplyr)
library(data.table)
library(tidyverse)
library(readxl)

# install.packages('splitstackshape')
# install.packages('janitor')
library(splitstackshape)
library(janitor)
library(stringr)
library(ggplot2)

